version: 2

updates:
  - package-ecosystem: gomod
    directory: /go
    schedule:
      interval: weekly
    labels:
      - dependencies
      - go

  - package-ecosystem: npm
    directory: /ts
    schedule:
      interval: weekly
    labels:
      - dependencies
      - typescript

  - package-ecosystem: pip
    directory: /py
    schedule:
      interval: weekly
    labels:
      - dependencies
      - python

  - package-ecosystem: cargo
    directory: /rs
    schedule:
      interval: weekly
    labels:
      - dependencies
      - rust

  - package-ecosystem: composer
    directory: /php
    schedule:
      interval: weekly
    labels:
      - dependencies
      - php

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci
